### PR TITLE
fix(tagwall): accommodate truncation in tags and list items

### LINKED ISSUE #511: TagWallFilter: long tags are not truncated & overflow their container
**Expected behavior -**

A long tag, either in the top filter area or in the bottom list area, should be truncated with an ellipsis.

**Actual behavior -**

Very long tags, in both the top filter area and the bottom list area, are not truncated and overflow their containers.

### Steps for reproducing

Check out the storybook & add very long tags:

https://ibm-security.carbondesignsystem.com/?path=/story/patterns-tagwallfilter--tagwall-with-filter-list-for-multiselect

### PR DESCRIPTION
**Pull request by jendowns**
## Affected issues

- Resolves #511 

## Proposed changes

- truncate tags in `TagWall` to 40ex per input from design
- truncate list items in `TagWall` to width of container
- update storybook demo to show what happens with long strings

## Testing instructions

- The `TagWall` demo has a long string now, so you can see how it appears when truncated. You can then remove the tag, returning it the list below, and see how it appears truncated in the list of options.

### CODE REVIEW

File: src/components/TagWall/TagWall.js [hunk 1]
```diff
@@ -71,7 +74,9 @@ const TagWall = ({
             removeBtnLabel={TAG_WALL_REMOVE_BUTTON}
             type="gray"
           >
-            {itemToString(item)}
+            <span className={`${carbonPrefix}text-truncate--end`}>
```
Comment (SimonFinney) [inline src/components/TagWall/TagWall.js:77]: Awesome! If we're applying the Carbon truncation helper class here, we should also import their partial (I believe it's called `globals/scss/helper-classes`) in `TagWall/_index.scss` to ensure that the styles will be compiled for individual component imports.

File: src/components/TagWall/_mixins.scss [hunk 2]
```diff
@@ -14,5 +14,10 @@
 
   > #{$tag--interactive__namespace} {
     margin-right: $carbon--spacing-03;
+    max-width: 40ex;
```
Comment (SimonFinney) [inline src/components/TagWall/_mixins.scss:17]: 👏

File: src/components/TagWallFilter/Filter/Filter.js [hunk 3]
```diff
@@ -135,7 +135,9 @@ class Filter extends React.Component {
             className={`${namespace}__list-item__entry`}
             aria-labelledby={itemProps.id}
           >
-            {itemText}
+            <span className={`${carbonPrefix}text-truncate--end`}>
```
Comment (SimonFinney) [inline src/components/TagWallFilter/Filter/Filter.js:138]: Similar comment to https://github.com/carbon-design-system/ibm-security/pull/513/files#r416481413

**Comment by SimonFinney** [comment]
Thanks @jendowns - Everything behaves great! I have one suggestion related to style imports

File: src/components/TagWall/TagWall.js (hunk 1 above)
Comment (jendowns) [reply src/components/TagWall/TagWall.js:77]: Thanks! I think I'll keep using their helper class here (with the correct import of course). Otherwise I would need to still keep the `span` & create our own class to apply the `text-overflow` mixin to. Just seems easier this way.

**Comment by jendowns** [comment]
@SimonFinney are you all right with me applying a `title` attribute to the truncated text wrapper? (the attribute would be present for all, regardless of whether the text is actually truncated)

**Comment by SimonFinney** [comment]
@jendowns That makes sense to me!

**Comment by jendowns** [comment]
Thanks @SimonFinney this is ready to review again 👍
