### PR TITLE
fix(nav): update type checking for rhl

### LINKED ISSUE #511: TagWallFilter: long tags are not truncated & overflow their container
**Expected behavior -**

A long tag, either in the top filter area or in the bottom list area, should be truncated with an ellipsis.

**Actual behavior -**

Very long tags, in both the top filter area and the bottom list area, are not truncated and overflow their containers.

### Steps for reproducing

Check out the storybook & add very long tags:

https://ibm-security.carbondesignsystem.com/?path=/story/patterns-tagwallfilter--tagwall-with-filter-list-for-multiselect

### LINKED ISSUE #515: Toolbar menus (expandable) do not render correctly
## Bug -
1) Try the sample at https://ibm-security.carbondesignsystem.com/?path=/story/patterns-toolbar--default.  Observe that the expandable "> Section 1" is generated properly and can be expanded.

2) Observe that the code that's generated includes a `<div class="security--nav__list__item__link">`.
Get the latest v1.22.0 from today and do the same sample as found at https://ibm-security.carbondesignsystem.com/?path=/story/patterns-toolbar--default.  Observe that the code that's generated does **not** include a `<div class="security--nav__list__item__link">` and the menu doesn't render correctly.

**Expected behavior -**
Should render like the sample at the sample at https://ibm-security.carbondesignsystem.com/?path=/story/patterns-toolbar--default.  Please see screenshot.

**Actual behavior -**
Please see screenshot.

### Steps for reproducing
1) Try the sample at https://ibm-security.carbondesignsystem.com/?path=/story/patterns-toolbar--default without changing anything.

### Screenshots
ToolbarGeneratingProperly
ToolbarNotGeneratingProperly

### Affected browsers

Chrome Windows 81.0.4044.129 (Official Build) (64-bit)

### Optional information

**Version -** v1.22.0 from today (April 28, 2020)

### PR DESCRIPTION
**Pull request by jendowns**
## Affected issues

- Resolves #515

## Proposed changes

- ~Create an imported component before checking its type in order to fix rendering issue with RHL. See https://github.com/carbon-design-system/carbon/pull/5929 for more context~ I ended up comparing the *name* of the component instead.

### CODE REVIEW

File: src/components/Nav/Nav.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ import { getComponentNamespace } from '../../globals/namespace';
 
 export const navNamespace = getComponentNamespace('nav');
 
-const { forEach, map } = Children;
```
Comment (jendowns) [inline src/components/Nav/Nav.js:19]: This abstraction was confusing for me in context further down because `forEach` and `map` are language features. I think it would help to remove this.

**Comment by jendowns** [comment]
Hey @SimonFinney this is ready to review. If you need an rhl environment to test with, I created a repo here: https://github.com/jendowns/rhl-template
